In [1]:
import numpy as np
a=np.array([13,4,2])
a

array([13,  4,  2])

In [2]:
a.shape

(3,)

In [3]:
a.ndim

1

In [4]:
a.size

3

In [5]:
a=np.array([1,2,3])
b=np.array([4,8,9])
print(a-b)

[-3 -6 -6]


In [6]:
print(a+b)

[ 5 10 12]


In [7]:
print(a*b)

[ 4 16 27]


In [8]:
a=np.array([10.3,10.4])
np.abs(a)

array([10.3, 10.4])

In [9]:
a=np.array([90,1,4,10,2])
np.sort(a)

array([ 1,  2,  4, 10, 90])

In [10]:
np.sort(a)[::-1]

array([90, 10,  4,  2,  1])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
a=np.array([1,4,7,8])
np.sum(a)

20

In [14]:
np.max(a)

8

In [15]:
np.mean(a)

5.0

In [16]:
np.min(a)

1

In [17]:
np.median(a)

5.5

In [18]:
a=np.arange(0,20,3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [19]:
a=np.linspace(0,20,3)
a

array([ 0., 10., 20.])

In [20]:
a=np.array([8,7,7,8])
np.unique(a)

array([7, 8])

In [21]:
np.random.randint(0,10,10)

array([8, 0, 8, 3, 3, 6, 1, 5, 3, 0])

In [23]:
np.random.seed(7)
np.random.randint(0,10,3)

array([4, 9, 6])

In [26]:
a=np.random.choice([1,3,2],size=(3,2))
a

array([[1, 3],
       [2, 1],
       [3, 2]])

In [28]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [36]:
import pandas as pd
d=pd.read_csv("C:/Users/HP/Desktop/ds_salaries.csv")
d

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

In [38]:
d.dropna()

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]

In [42]:
d.drop(d.iloc[:,1:2],inplace=True,axis=1)
d

Unnamed: 0                   job_title  salary salary_currency  \
0             0              Data Scientist   70000             EUR   
1             1  Machine Learning Scientist  260000             USD   
2             2           Big Data Engineer   85000             GBP   
3             3        Product Data Analyst   20000             USD   
4             4   Machine Learning Engineer  150000             USD   
..          ...                         ...     ...             ...   
602         602               Data Engineer  154000             USD   
603         603               Data Engineer  126000             USD   
604         604                Data Analyst  129000             USD   
605         605                Data Analyst  150000             USD   
606         606                AI Scientist  200000             USD   

     salary_in_usd employee_residence  remote_ratio company_location  \
0            79833                 DE             0               DE   
1           260000                 JP             0               JP   
2           109024                 GB            50               GB   
3            20000                 HN             0               HN   
4           150000                 US            50               US   
..             ...                ...           ...              ...   
602         154000                 US           100               US   
603         126000                 US           100               US   
604         129000                 US             0               US   
605         150000                 US           100               US   
606         200000                 IN           100               US   

    company_size  
0              L  
1              S  
2              M  
3              S  
4              L  
..           ...  
602            M  
603            M  
604            M  
605            M  
606            L  

[607 rows x 9 columns]

In [50]:
d.replace(to_replace=np.NaN,value=5)

Unnamed: 0                   job_title  salary salary_currency  \
0             0              Data Scientist   70000             EUR   
1             1  Machine Learning Scientist  260000             USD   
2             2           Big Data Engineer   85000             GBP   
3             3        Product Data Analyst   20000             USD   
4             4   Machine Learning Engineer  150000             USD   
..          ...                         ...     ...             ...   
602         602               Data Engineer  154000             USD   
603         603               Data Engineer  126000             USD   
604         604                Data Analyst  129000             USD   
605         605                Data Analyst  150000             USD   
606         606                AI Scientist  200000             USD   

     salary_in_usd employee_residence  remote_ratio company_location  \
0            79833                 DE             0               DE   
1           260000                 JP             0               JP   
2           109024                 GB            50               GB   
3            20000                 HN             0               HN   
4           150000                 US            50               US   
..             ...                ...           ...              ...   
602         154000                 US           100               US   
603         126000                 US           100               US   
604         129000                 US             0               US   
605         150000                 US           100               US   
606         200000                 IN           100               US   

    company_size  
0              L  
1              S  
2              M  
3              S  
4              L  
..           ...  
602            M  
603            M  
604            M  
605            M  
606            L  

[607 rows x 9 columns]

In [51]:
d.replace(to_replace=[],value=6)

Unnamed: 0                   job_title  salary salary_currency  \
0             0              Data Scientist   70000             EUR   
1             1  Machine Learning Scientist  260000             USD   
2             2           Big Data Engineer   85000             GBP   
3             3        Product Data Analyst   20000             USD   
4             4   Machine Learning Engineer  150000             USD   
..          ...                         ...     ...             ...   
602         602               Data Engineer  154000             USD   
603         603               Data Engineer  126000             USD   
604         604                Data Analyst  129000             USD   
605         605                Data Analyst  150000             USD   
606         606                AI Scientist  200000             USD   

     salary_in_usd employee_residence  remote_ratio company_location  \
0            79833                 DE             0               DE   
1           260000                 JP             0               JP   
2           109024                 GB            50               GB   
3            20000                 HN             0               HN   
4           150000                 US            50               US   
..             ...                ...           ...              ...   
602         154000                 US           100               US   
603         126000                 US           100               US   
604         129000                 US             0               US   
605         150000                 US           100               US   
606         200000                 IN           100               US   

    company_size  
0              L  
1              S  
2              M  
3              S  
4              L  
..           ...  
602            M  
603            M  
604            M  
605            M  
606            L  

[607 rows x 9 columns]

In [53]:
a=pd.read_csv("C:/Users/HP/Desktop/ds_salaries.csv")
b=a.dropna(how="all")
b

Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT   
1             1       2020               SE              FT   
2             2       2020               SE              FT   
3             3       2020               MI              FT   
4             4       2020               SE              FT   
..          ...        ...              ...             ...   
602         602       2022               SE              FT   
603         603       2022               SE              FT   
604         604       2022               SE              FT   
605         605       2022               SE              FT   
606         606       2022               MI              FT   

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833   
1    Machine Learning Scientist  260000             USD         260000   
2             Big Data Engineer   85000             GBP         109024   
3          Product Data Analyst   20000             USD          20000   
4     Machine Learning Engineer  150000             USD         150000   
..                          ...     ...             ...            ...   
602               Data Engineer  154000             USD         154000   
603               Data Engineer  126000             USD         126000   
604                Data Analyst  129000             USD         129000   
605                Data Analyst  150000             USD         150000   
606                AI Scientist  200000             USD         200000   

    employee_residence  remote_ratio company_location company_size  
0                   DE             0               DE            L  
1                   JP             0               JP            S  
2                   GB            50               GB            M  
3                   HN             0               HN            S  
4                   US            50               US            L  
..                 ...           ...              ...          ...  
602                 US           100               US            M  
603                 US           100               US            M  
604                 US             0               US            M  
605                 US           100               US            M  
606                 IN           100               US            L  

[607 rows x 12 columns]